CREATE DATABASE IF NOT EXISTS portal_of_future CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE portal_of_future;

CREATE TABLE IF NOT EXISTS app_state (
  id INT PRIMARY KEY,
  data LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
